### ISSUE TITLE
Why not using C++1x

### ISSUE THREAD

**Issue by messi1** [Infineon/hall-switch#1]
Hi 
I have checked your C++ code.
I'm wondering why you are not using C++1x. There is no reason not to use it with bare metal.
As far as I know with Dave4 or Arduino IDE you can use either the GCC or Clang compiler.
Since C++11 you can use e.g. enum class, inline initialization, ....
I highly recommend this book if you are going to programm MCU with C++
https://www.springer.com/de/book/9783662567173

**Comment by ArkajyotiChatterjee** [comment]
Hello Jeurgen,
The book you recommend is indeed a great starting point to program MCU with C++.
And yes we know that Arduino IDE does support GCC & Clang and C++1x .
But if you look at the codebase for this library or any other library, though its C++ but in reality its C with Classes.
There is no reason why we could not use it, but if you see the Template/Test Library from Arduino.cc , it is essentially how our library looks like.
Again , as I mentioned , yes, we could write the library in C++1x , but current implementation is just in accordance with what you find in Adafruit/Sparkfun or in classical Arduino Libraries.
Thanks again for the link and your question, I would be closing this issue.
Regards,
Arka

**Comment by messi1** [comment]
Hi Arka
thanks for the clarification.
